=== janamarti/OR-lab1/Schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://or.fer.unizg.hr/ordrzave.json",
  "type": "array",
  "title": "OR Države",
  "description": "Skup podataka o državama za laboratorijske vježbe iz predmeta Otvoreno računarstvo.",
  "items": {
    "type": "object",
	"title": "država",
	"description": "Objekt koji opisuje jednu državu",
	"required": [
		"naziv",
        "iso_3116_alpha_3",
        "glavni_grad",
        "jezici",
        "valuta",
        "pozivni_broj",
        "top_level_domena",
        "naziv_himne",
        "povrsina",
        "strana_voznje",
        "wikipedia_handle"
    ],
    "properties": {
      "naziv": {
        "type": "string",
		"title": "Naziv države",
		"description": "Skraćeni naziv države, a ne puni, službeni naziv"
      },
      "iso_3116_alpha_3": {
        "type": "string",
		"title": "ISO 3116 alpha-3 kôd države",
		"description": "Troslovni kôd države opisan ISO 3116 alpha-3 standardom"
      },
      "glavni_grad": {
        "type": "string",
		"title": "Glavni grad",
		"description": "Glavni grad"
      },
      "jezici": {
        "type": "array",
		"title": "Službeni jezici",
		"description": "Službeni jezici",
		"required": [
            "iso_639",
            "naziv"
          ],
        "items": {
          "type": "object",
		  "title": "Službeni jezici",
		  "description": "Službeni jezici",
          "properties": {
            "iso_639": {
              "type": "string",
			  "title": "ISO 639 kôd jezika",
			  "description": "Troslovni kôd jezika opisan ISO 639 standardom"
            },
            "naziv": {
              "type": "string",
			  "title": "Naziv jezika",
			  "description": "Naziv jezika"
            }
          }
        }
      },
      "valuta": {
        "type": "string",
		"title": "Valuta",
		"description": "Službena valuta države"
      },
      "pozivni_broj": {
        "type": "string",
		"title": "Pozivni broj",
		"description": "pozivni broj ili predbroj države, propisan standardima E.123 i E.164. tijela ITU-T"
      },
      "top_level_domena": {
        "type": "string",
		"title": "Top level domena",
		"description": "Top-level ili vršna domena propisana od IANA-e, odgovara ISO 3116 alpha-2 dvoslovnom kôdu"
      },
      "naziv_himne": {
        "type": "string",
		"title": "Naziv himne",
		"description": "Naziv himne"
      },
      "povrsina": {
        "type": "integer",
		"title": "Površina",
		"description": "Površina u kilometrima četvornim"
      },
      "strana_voznje": {
        "type": "string",
		"title": "Strana vožnje",
		"description": "Strana vožnje jedinstvena unutar granica jedne države, može biti ili lijeva ili desna"
      },
      "wikipedia_handle": {
        "type": "string",
		"title": "Wiki handle",
		"description": "jedinstveni Wikipedia identifikator stranice"
      }
    }
  }
}

=== janamarti/OR-lab1/filtriraneDrzave.json
[
  {
    "naziv": "Palau",
    "iso_3116_alpha_3": "PLW",
    "glavni_grad": "Ngerulmud",
    "jezici": [
      {
        "iso_639": "eng",
        "naziv": "engleski"
      },
      {
        "iso_639": "pau",
        "naziv": "palauski"
      },
      {
        "iso_639": "jpn",
        "naziv": "japanski"
      },
      {
        "iso_639": "tox",
        "naziv": "tobijski"
      },
      {
        "iso_639": "sov",
        "naziv": "sonsorolezijski"
      }
    ],
    "valuta": "USD",
    "pozivni_broj": "+680",
    "top_level_domena": ".pw",
    "naziv_himne": "Belau rekid",
    "povrsina": 459,
    "strana_voznje": "desna",
    "wikipedia_handle": "Palau"
  },
  {
    "naziv": "Honduras",
    "iso_3116_alpha_3": "HND",
    "glavni_grad": "Tegucigalpa",
    "jezici": [
      {
        "iso_639": "spa",
        "naziv": "španjolski"
      }
    ],
    "valuta": "HNL",
    "pozivni_broj": "+504",
    "top_level_domena": ".hn",
    "naziv_himne": "Himno Nacional de Honduras",
    "povrsina": 112492,
    "strana_voznje": "desna",
    "wikipedia_handle": "Honduras"
  },
  {
    "naziv": "Novi Zeland",
    "iso_3116_alpha_3": "NZL",
    "glavni_grad": "Wellington",
    "jezici": [
      {
        "iso_639": "eng",
        "naziv": "engleski"
      },
      {
        "iso_639": "mri",
        "naziv": "maorski"
      },
      {
        "iso_639": "nzs",
        "naziv": "novozelandski znakovni"
      }
    ],
    "valuta": "NZD",
    "pozivni_broj": "+64",
    "top_level_domena": ".nz",
    "naziv_himne": "God Defend New Zealand",
    "povrsina": 268021,
    "strana_voznje": "lijeva",
    "wikipedia_handle": "New_Zealand"
  },
  {
    "naziv": "Ekvador",
    "iso_3116_alpha_3": "ECU",
    "glavni_grad": "Quito",
    "jezici": [
      {
        "iso_639": "spa",
        "naziv": "španjolski"
      }
    ],
    "valuta": "USD",
    "pozivni_broj": "+593",
    "top_level_domena": ".ec",
    "naziv_himne": "Salve, Oh Patria",
    "povrsina": 283561,
    "strana_voznje": "desna",
    "wikipedia_handle": "Ecuador"
  }
]
